name: Deploy to Review Branch

on:
  push:
    branches: [ "feature/**", "fix/**", "dorkem", "main", "refactor/**" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set Up JDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Create application-dev.yml
        env:
          APP_DEV_YML: ${{ secrets.APP_DEV_YML }}
        run: |
          mkdir -p src/main/resources
          printf '%s' "$APP_DEV_YML" > src/main/resources/application-dev.yml

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: store artifacts (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
          retention-days: 1

      - name: store artifacts (Frontend)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/
          retention-days: 1

      - name: store artifacts (deploy.sh)
        uses: actions/upload-artifact@v4
        with:
          name: deploy-script
          path: scripts/deploy.sh
          retention-days: 1

  deploy-app-server-1:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: download artifacts (JAR)
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs/

      - name: download artifacts (deploy.sh)
        uses: actions/download-artifact@v4
        with:
          name: deploy-script
          path: scripts/

      - name: Transfer deploy.sh to the app-01
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.APP_SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "scripts/deploy.sh"
          target: "/home/ec2-user/woowahan-delivery"
          strip_components: 1

      - name: Transfer JAR to the app-01
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.APP_SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ec2-user/woowahan-delivery"
          strip_components: 2

      - name: Deploy to app-01 (dev)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.APP_SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /home/ec2-user/woowahan-delivery
            chmod +x deploy.sh
            ./deploy.sh ${{ secrets.APP_SERVER_HOST_1 }} dev server1

  deploy-app-server-2:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: download artifacts (JAR)
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs/

      - name: download artifacts (deploy.sh)
        uses: actions/download-artifact@v4
        with:
          name: deploy-script
          path: scripts/

      - name: Transfer deploy.sh to the app-02
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.APP_SERVER_HOST_2 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "scripts/deploy.sh"
          target: "/home/ec2-user/woowahan-delivery"
          strip_components: 1

      - name: Transfer JAR to the app-02
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.APP_SERVER_HOST_2 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ec2-user/woowahan-delivery"
          strip_components: 2

      - name: Deploy to app-02 (dev)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.APP_SERVER_HOST_2 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /home/ec2-user/woowahan-delivery
            chmod +x deploy.sh
            ./deploy.sh ${{ secrets.APP_SERVER_HOST_2 }} dev server2

  deploy-frontend:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: download artifacts (Frontend)
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/

      - name: Transfer Frontend to the LB
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.LB_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "frontend/dist/**"
          target: "/var/www/woowahan-delivery"
          strip_components: 2
